railwayweb/src/main/java/com/javaschool/railwayweb/model/Route.java
package com.javaschool.railwayweb.model;

import java.io.Serializable;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

@Entity
public class Route implements Serializable {
	private static final long serialVersionUID = 2658788702421739720L;
	@Id
	@GeneratedValue
	private long id;
	@Column
	@NotNull(message = "Route name should be non-empty")
	@Size(min = 4, max = 50, message = "Name length must be from 4 to 50")
	private String routeName;

	@OneToMany (mappedBy = "key.route", fetch = FetchType.EAGER)
	private List<RouteLines> routeLines;
	
	public List<RouteLines> getRouteLines() {
		return routeLines;
	}
	public void setRouteLines(List<RouteLines> routeLines) {
		this.routeLines = routeLines;
	}

	public String getRouteName() {
		return routeName;
	}
	public void setRouteName(String routeName) {
		this.routeName = routeName;
	}
	
	public long getId() {
		return id;
	}
	public String toString() {
		return id + ". " + routeName; 
	}
	
	public Station getStationTo() {
		return routeLines.get(routeLines.size() - 1).getStation();
	}
	
}

railwayweb/src/main/java/com/javaschool/railwayweb/model/Ticket.java
package com.javaschool.railwayweb.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

@Entity
public class Ticket implements Serializable{
	private static final long serialVersionUID = 2L;
	@Id
	@GeneratedValue
	private long id;
	@ManyToOne
	@JoinColumn(name = "ScheduleId")
	private Schedule schedule;
	@ManyToOne
	@JoinColumn(name = "PassengerId")
	private Passenger passenger;
	
	@Column
	private int pointNumFrom;
	@Column
	private int pointNumTo;
	
	public long getId() {
		return id;
	}
	public Schedule getSchedule() {
		return schedule;
	}
	public void setSchedule(Schedule schedule) {
		this.schedule = schedule;
	}
	public Passenger getPassenger() {
		return passenger;
	}
	public void setPassenger(Passenger passenger) {
		this.passenger = passenger;
	}
	public int getPointNumFrom() {
		return pointNumFrom;
	}
	public void setPointNumFrom(int pointNumFrom) {
		this.pointNumFrom = pointNumFrom;
	}
	public int getPointNumTo() {
		return pointNumTo;
	}
	public void setPointNumTo(int pointNumTo) {
		this.pointNumTo = pointNumTo;
	}
	
}

railwayweb/src/main/java/com/javaschool/railwayweb/controllers/PassengerListController.java
package com.javaschool.railwayweb.controllers;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

import com.javaschool.railwayweb.dto.PassengerTicketDto;
import com.javaschool.railwayweb.service.PassengerListService;

@Controller
@RequestMapping("/passengerList")
public class PassengerListController {
	@Autowired
	PassengerListService passengerListService;
	
	@RequestMapping
	@Transactional
	public String showPassengerList(Model model, @RequestParam("id") Integer id) {
		List<PassengerTicketDto> passengerList = passengerListService.getPassengerList(id);
		model.addAttribute("passengerList", passengerList);
		return "ticket/passengerList";
	}
}

railwayweb/src/main/webapp/pages/ticket/buySuccess.jsp
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<head>
    <title>Ticket</title>
	<spring:url value="/css/bootstrap/bootstrap.min.css" var="bootstrapMinUrl"></spring:url>    
	<link href="${bootstrapMinUrl}" rel="stylesheet"/>
	<spring:url value="/css/addSchedule.css" var="addScheduleUrl"></spring:url>
	<link href="${addScheduleUrl}" rel="stylesheet"/>
	<spring:url value="/css/rheader.css" var="rheaderUrl"></spring:url>
	<link href="${rheaderUrl}" rel="stylesheet">	
</head>
<body>
    <div class="container-fluid">
      <div class="row">
		<jsp:include page="../sidebar.jsp"></jsp:include>

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        
        	<c:if test="${empty msg}">
        		<div class="rform-centered col-md-8">
        			<h3> Ticket bought! </h3>
        			<br/><br/>
        			<h4> Information: </h4>
	        		<table class="table table-bordered">
	        			<tr>
	        				<td> First name: </td> <td> ${passengerTicket.firstname}</td>
	        			</tr>
	        			<tr>
	        				<td> Last name: </td> <td> ${passengerTicket.lastname}</td>
	        			</tr>
	        			<tr>
	        				<td> Station from: </td> <td> ${passengerTicket.stationFrom}</td>
	        			</tr>
	        			<tr>
	        				<td> Station to: </td> <td> ${passengerTicket.stationTo} </td>
	        			</tr>
	        		</table>
        		</div>
        	</c:if>
        	<c:if test="${not empty msg}">
        		<h3>${msg}</h3>
        	</c:if>

		</div>	<!-- main -->
      </div>	<!-- row -->
    </div>		<!-- container-fluid -->
	
<spring:url value="/js/jquery-2.1.0.js" var="jqueryUrl"></spring:url>
<script src="${jqueryUrl}"></script>
<spring:url value="/js/bootstrap/bootstrap.min.js" var="bootstrapJsUrl"/>
<script src="${bootstrapJsUrl}"></script>
	
</body>

railwayweb/src/main/webapp/pages/ticket/passengerList.jsp
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<!DOCTYPE html>
<html>
  <head>
    <title>Passenger list</title>
	<spring:url value="/css/bootstrap/bootstrap.min.css" var="bootstrapMinUrl"></spring:url>    
	<link href="${bootstrapMinUrl}" rel="stylesheet"/>
	<spring:url value="/css/rheader.css" var="rheaderUrl"></spring:url>
	<link href="${rheaderUrl}" rel="stylesheet">
	<spring:url value="/css/rtable.css" var="rTableCss"></spring:url>
	<link href="${rTableCss}" rel="stylesheet">
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
		<jsp:include page="../sidebar.jsp"></jsp:include>

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        
        	<div class="rheader">
        		<div class="rheader-buttons">
        			<strong>Total passengers: ${passengerList.size()}</strong>
        		</div>
        	</div>
        	
        	<div id="tableContainer">
        	<table class="table rtable">
        		<tr>
        			<th>First name</th>
        			<th>Last name</th>
        			<th>Birthdate</th>
        			<th>Station from</th>
        			<th>Station to</th>        			
        		</tr>
        		<c:forEach items="${passengerList}" var="tableRow">
        			<tr>
        				<td>${tableRow.firstname}</td>
        				<td>${tableRow.lastname}</td>
        				<td>${tableRow.birthdate}</td>
        				<td>${tableRow.stationFrom}</td>
        				<td>${tableRow.stationTo}</td>
        			</tr>
        		</c:forEach>
        	</table>
        	</div>
        
		</div>	<!-- main -->        
      </div>	<!-- row -->
    </div>		<!-- container-fluid -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <spring:url value="/js/jquery-2.1.0.js" var="jqueryUrl"></spring:url>
    <script src="${jqueryUrl}"></script>
    <spring:url value="/js/bootstrap/bootstrap.min.js" var="bootstrapJsUrl"/>
    <script src="${bootstrapJsUrl}"></script>
  </body>
</html>