railwayweb/src/main/java/com/javaschool/railwayweb/model/Route.java
package com.javaschool.railwayweb.model;

import java.io.Serializable;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

@Entity
public class Route implements Serializable {
	private static final long serialVersionUID = 2658788702421739720L;
	@Id
	@GeneratedValue
	private long id;
	@Column
	@NotNull(message = "Route name should be non-empty")
	@Size(min = 4, max = 50, message = "Name length must be from 4 to 50")
	private String routeName;

	@OneToMany (mappedBy = "key.route", fetch = FetchType.EAGER)
	private List<RouteLines> routeLines;
	
	public List<RouteLines> getRouteLines() {
		return routeLines;
	}
	public void setRouteLines(List<RouteLines> routeLines) {
		this.routeLines = routeLines;
	}

	public String getRouteName() {
		return routeName;
	}
	public void setRouteName(String routeName) {
		this.routeName = routeName;
	}
	
	public long getId() {
		return id;
	}
	public String toString() {
		return id + ". " + routeName; 
	}
	
	public Station getStationTo() {
		return routeLines.get(routeLines.size() - 1).getStation();
	}
	
}

railwayweb/src/main/java/com/javaschool/railwayweb/model/Schedule.java
package com.javaschool.railwayweb.model;

import java.io.Serializable;
import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

import org.joda.time.DateTime;
import org.joda.time.Duration;
import org.joda.time.LocalTime;
import org.springframework.format.annotation.DateTimeFormat;

@Entity
@Table(uniqueConstraints = {
		@UniqueConstraint(columnNames = {"TemplateId", "dateStart"})
})
public class Schedule implements Serializable {
	private static final long serialVersionUID = -222742999167295180L;
	@Id
	@GeneratedValue
	private long id;
	@Column
	@Min(value = 1, message = "Seats num must be greater than or equal to 1")
	private int seats;
	
	@ManyToOne
	@JoinColumn(name = "TemplateId")
	private Route route;
	@Column
	@Temporal(TemporalType.DATE)
	@NotNull(message = "Start date is mandatory field")
	@DateTimeFormat(pattern = "dd.MM.yyyy")	
	private Date dateStart;
	
	@OneToMany(mappedBy="schedule")
	private Set<Ticket> tickets;
	
	public Set<Ticket> getTickets() {
		return tickets;
	}
	public void setTickets(Set<Ticket> tickets) {
		this.tickets = tickets;
	}
	
	public long getId() {
		return id;
	}
	public int getSeats() {
		return seats;
	}
	public void setSeats(int seats) {
		this.seats = seats;
	}	
	public Route getRoute() {
		return route;
	}
	public void setRoute(Route route) {
		this.route = route;
	}
	public Date getDateStart() {
		return dateStart;
	}
	public void setDateStart(Date dateStart) {
		this.dateStart = dateStart;
	}
	
	// TODO add comment
	public Date getStationDateTime(Station s) {
		long stationId = 0;
		if (s != null)
			stationId = s.getId();
		DateTime startDt = new DateTime(dateStart);
		Date lastTime = null;
		for (RouteLines rl : route.getRouteLines()) {
			if (lastTime != null) {
				long delta = rl.getTimePass().getTime() - lastTime.getTime();
				if (delta < 0)
					delta += 24 * 3600 * 1000;
				startDt = startDt.plus(new Duration(delta));
			}
			else {
				LocalTime departTime = new LocalTime(rl.getTimePass());
				startDt = startDt.plus(departTime.getMillisOfDay());
			}
			lastTime = rl.getTimePass();
			if (rl.getStation().getId() == stationId)
				break;
		}
		return startDt.toDate();
	}
	
	public Date getStationToDateTime() {
		return this.getStationDateTime(null);
	}
	
	public Date getStationFromDateTime() {
		return this.getStationDateTime(route.getRouteLines().get(0).getStation());	
	}
	
	
	public int getEmptySeats() {		
		int ticketsSell = tickets.size();
		return seats - ticketsSell;
	}
	
	public boolean haveTimeToBuy() {
		DateTime currentDT = new DateTime();
		DateTime departDT = new DateTime(dateStart);
		LocalTime departTime = new LocalTime(route.getRouteLines().get(0).getTimePass());
		departDT = departDT.plus(departTime.getMillisOfDay());
		Duration duration = new Duration(currentDT, departDT);
		if (duration.isShorterThan(new Duration(10 * 60 * 1000L)))
			return false;
		return true;		
	}
}

railwayweb/src/main/java/com/javaschool/railwayweb/model/ScheduleFilter.java
package com.javaschool.railwayweb.model;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class ScheduleFilter implements Serializable {
	private static final long serialVersionUID = 345441016991304225L;
	@DateTimeFormat(pattern = "dd.MM.yyyy")
	public Date dateStart;
	public long stationIdFrom;
	public long stationIdTo;
	
	public Date getDateStart() {
		return dateStart;
	}
	public void setDateStart(Date dateStart) {
		this.dateStart = dateStart;
	}
	public long getStationIdFrom() {
		return stationIdFrom;
	}
	public void setStationIdFrom(long stationIdFrom) {
		this.stationIdFrom = stationIdFrom;
	}
	public long getStationIdTo() {
		return stationIdTo;
	}
	public void setStationIdTo(long stationIdTo) {
		this.stationIdTo = stationIdTo;
	}
	@Override
	public String toString() {
		String ret;
		if (dateStart == null)
			ret = "null";
		else
			ret = Global.dateFormat.format(dateStart);
		ret = "[dateStart: " + ret;
		return ret +
				", stationFrom: " + stationIdFrom +
				", stationTo: " + stationIdTo + "]";
	}
}

railwayweb/src/main/java/com/javaschool/railwayweb/controllers/AddScheduleController.java
package com.javaschool.railwayweb.controllers;

import java.util.Date;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import com.javaschool.railwayweb.dao.RouteDao;
import com.javaschool.railwayweb.dao.ScheduleDao;
import com.javaschool.railwayweb.model.Schedule;
import com.javaschool.railwayweb.service.ScheduleService;

@RequestMapping("/schedule/add")
@Controller
public class AddScheduleController {
	@Autowired
	RouteDao routeDao;
	@Autowired
	ScheduleService scheduleService;
	
	@RequestMapping(method=RequestMethod.GET)
	public String showPage(Model model, @ModelAttribute("errorMsg") String errorMsg) {
		model.addAttribute("schedule", new Schedule());
		model.addAttribute("routeList", routeDao.getAll());
		model.addAttribute("msg", errorMsg);
		return "schedule/addSchedule";
	}
	
	@RequestMapping(method=RequestMethod.POST)
	public String addSchedule(Integer route,
				@DateTimeFormat(pattern="dd.MM.yyyy") Date dateStart,
				Integer seats, Model model, RedirectAttributes redirectAttributes) {
		String result = scheduleService.addSchedule(routeDao.find(route), dateStart, seats);
		if (result.equals(""))
			return "redirect:/";
		else {
			redirectAttributes.addAttribute("errorMsg", result);
			return "redirect:/schedule/add";
		}
	}
}

railwayweb/src/main/java/com/javaschool/railwayweb/controllers/FullScheduleController.java
package com.javaschool.railwayweb.controllers;

import java.text.SimpleDateFormat;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

import com.javaschool.railwayweb.dao.ScheduleDao;
import com.javaschool.railwayweb.dao.StationDao;
import com.javaschool.railwayweb.dto.ScheduleRouteLineDto;
import com.javaschool.railwayweb.model.Schedule;
import com.javaschool.railwayweb.model.ScheduleFilter;
import com.javaschool.railwayweb.model.Station;
import com.javaschool.railwayweb.service.ScheduleService;

@Controller
@RequestMapping({"/"})
public class FullScheduleController {
	
	@Autowired
	ScheduleDao scheduleDao;
	@Autowired
	StationDao stationDao;
	@Autowired
	ScheduleService scheduleService;
	
	@RequestMapping
	public String showSchedulePage(ScheduleFilter scheduleFilter, Model model) {
		List<Schedule> scheduleList;
		if (scheduleFilter == null) {
			scheduleList = scheduleDao.getAll();
		}
		else {			
			scheduleList = scheduleDao.getFilteredSchedule(scheduleFilter);
		}
		model.addAttribute("scheduleList", scheduleList);
		model.addAttribute("applyFilter", scheduleFilter == null ? new ScheduleFilter() : scheduleFilter);
		List<Station> stationList = stationDao.getAll();
		Map<Long, String> stationMap = new LinkedHashMap<Long, String>();
		for (Station s : stationList) {
			stationMap.put(s.getId(), s.getName());
		}
		model.addAttribute("stationMap", stationMap);
		
		return "schedule/index";
	}
	
	@RequestMapping("/schedule/routeLines")
	public String showLines(Model model, @RequestParam("id") long id) {
		List<ScheduleRouteLineDto> srlDtoList = scheduleService.getScheduleRouteLines(id);
		model.addAttribute("scheduleRouteLines", srlDtoList);
		model.addAttribute("msg", "");
		Schedule schedule = scheduleDao.find(id);
		SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
		model.addAttribute("infoMsg", "Route: " + schedule.getRoute().getRouteName()
				+ ", departure date: " + sdf.format(schedule.getDateStart()));
		return "schedule/scheduleRouteLines";
	}
}

railwayweb/src/main/webapp/pages/schedule/fullScheduleTable.jsp
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>



	<table class="table table-striped rtable" id="fullScheduleTable">
		<tr>
			<th>Route</th>
			<th>Station from</th>
			<th>Station to</th>
			<th>Departure time</th>
			<th>Arrival time</th>
			<th></th>
		</tr>
		<c:forEach items = "${scheduleList}" var = "line">
			<tr>
				<td>${line.route.routeName}</td>
				<td>${line.route.routeLines.get(0).station.name}</td>
				<td>${line.route.stationTo.name}</td>
				<td><fmt:formatDate value="${line.stationFromDateTime}" pattern="dd.MM.yyyy HH:mm:ss"/></td>
				<td><fmt:formatDate value="${line.stationToDateTime}" pattern="dd.MM.yyyy HH:mm:ss"/></td>
				<spring:url value="/buyTicket/form?id=${line.id}" var="buyTicketUrl"/>
				<spring:url value="/passengerList?id=${line.id}" var="passengerListUrl"></spring:url>
				<spring:url value="/schedule/routeLines?id=${line.id}" var="scheduleRouteLinesUrl"></spring:url>
				<spring:url value="/img/buy-tickets-button2.png" var="buyTicketImg"></spring:url>
				<spring:url value="/img/list-button.png" var="stationListImg"></spring:url>
				<td>
					<sec:authorize access="isAuthenticated()">													
						<a href="${passengerListUrl}"><img alt="Passenger list" title="View passenger list" src="img/passenger-list-btn.png" height="30"></a>
					</sec:authorize>
					<a href="${scheduleRouteLinesUrl}"><img src="${stationListImg}" title="View station list" height="32"/></a>
					<c:if test="${line.haveTimeToBuy()}">
						<a href="${buyTicketUrl}"><img alt="Buy ticket" src="${buyTicketImg}" height="32"/></a>
					</c:if>					
				</td>
			</tr>
		</c:forEach>
	</table>

railwayweb/src/main/webapp/pages/schedule/scheduleFilterForm.jsp
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>


			<div id = "filters">
				<form:form method = "post" modelAttribute="applyFilter" class="form-inline" role="form">
					
						<div class="form-group">
								<form:select path="stationIdFrom" class="form-control">
									<form:option value="0" label="--Station from--"></form:option>
									<form:options items="${stationMap}"/>
								</form:select>
						</div>
						<div class="form-group">
								<form:select path="stationIdTo" class="form-control">
									<form:option value="0" label="--Station to--"></form:option>
									<form:options items="${stationMap}"/>
								</form:select>
						</div>
						<div class="input-group date col-md-4 form-group" id="dpFilter">
							<div style="float:left">
							<form:input path="dateStart" type="text" class="form-control" style="width: 75%"></form:input>
							<span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
							</div>							
						</div>
					
						<div class="form-group">
							<input type="submit" class="btn btn-success" value="Apply filter"/>
						</div>
					
				</form:form>				
			</div>
			